// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 01_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email, password_hash, phone_number, role
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, full_name, email, role, is_active, created_at
`

type CreateUserParams struct {
	FullName     string
	Email        string
	PasswordHash string
	PhoneNumber  pgtype.Text
	Role         RoleEnum
}

type CreateUserRow struct {
	ID        pgtype.UUID
	FullName  string
	Email     string
	Role      RoleEnum
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
		arg.PhoneNumber,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, password_hash, role, is_active 
FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	FullName     string
	Email        string
	PasswordHash string
	Role         RoleEnum
	IsActive     bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, full_name, email, phone_number, is_active, created_at 
FROM users 
WHERE role = 'customer' AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32
	Offset int32
}

type ListCustomersRow struct {
	ID          pgtype.UUID
	FullName    string
	Email       string
	PhoneNumber pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserOne = `-- name: UpdateUserOne :exec
SELECT id, full_name, email, password_hash, role, is_active 
FROM users 
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) UpdateUserOne(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserOne, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users 
SET is_active = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID       pgtype.UUID
	IsActive bool
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.IsActive)
	return err
}
