// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 02_user_profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateProfile = `-- name: CreateOrUpdateProfile :one
INSERT INTO user_profiles (
    user_id, date_of_birth, gender, bio, division, district, street_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (user_id) DO UPDATE SET
    date_of_birth = EXCLUDED.date_of_birth,
    gender = EXCLUDED.gender,
    bio = EXCLUDED.bio,
    division = EXCLUDED.division,
    district = EXCLUDED.district,
    street_address = EXCLUDED.street_address,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, date_of_birth, gender, bio, division, district, street_address, created_at, updated_at
`

type CreateOrUpdateProfileParams struct {
	UserID        pgtype.UUID
	DateOfBirth   pgtype.Date
	Gender        NullGenderEnum
	Bio           pgtype.Text
	Division      pgtype.Text
	District      pgtype.Text
	StreetAddress pgtype.Text
}

func (q *Queries) CreateOrUpdateProfile(ctx context.Context, arg CreateOrUpdateProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createOrUpdateProfile,
		arg.UserID,
		arg.DateOfBirth,
		arg.Gender,
		arg.Bio,
		arg.Division,
		arg.District,
		arg.StreetAddress,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Bio,
		&i.Division,
		&i.District,
		&i.StreetAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserId = `-- name: GetProfileByUserId :one
SELECT id, user_id, date_of_birth, gender, bio, division, district, street_address, created_at, updated_at FROM user_profiles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfileByUserId(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserId, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Bio,
		&i.Division,
		&i.District,
		&i.StreetAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
