// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 04_products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, name, slug, sku, description, short_description, 
    price, discount_price, quantity, low_stock_threshold, stock_status, 
    label, tags, images_url, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, category_id, name, slug, sku, description, short_description, price, discount_price, quantity, low_stock_threshold, stock_status, label, tags, images_url, is_active, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CategoryID        pgtype.UUID
	Name              string
	Slug              string
	Sku               string
	Description       string
	ShortDescription  string
	Price             pgtype.Numeric
	DiscountPrice     pgtype.Numeric
	Quantity          int32
	LowStockThreshold int32
	StockStatus       StockStatusEnum
	Label             ProductLabelEnum
	Tags              []string
	ImagesUrl         []string
	IsActive          bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.Description,
		arg.ShortDescription,
		arg.Price,
		arg.DiscountPrice,
		arg.Quantity,
		arg.LowStockThreshold,
		arg.StockStatus,
		arg.Label,
		arg.Tags,
		arg.ImagesUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.Quantity,
		&i.LowStockThreshold,
		&i.StockStatus,
		&i.Label,
		&i.Tags,
		&i.ImagesUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT p.id, p.category_id, p.name, p.slug, p.sku, p.description, p.short_description, p.price, p.discount_price, p.quantity, p.low_stock_threshold, p.stock_status, p.label, p.tags, p.images_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, c.name as category_name 
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.id = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductByIdRow struct {
	ID                pgtype.UUID
	CategoryID        pgtype.UUID
	Name              string
	Slug              string
	Sku               string
	Description       string
	ShortDescription  string
	Price             pgtype.Numeric
	DiscountPrice     pgtype.Numeric
	Quantity          int32
	LowStockThreshold int32
	StockStatus       StockStatusEnum
	Label             ProductLabelEnum
	Tags              []string
	ImagesUrl         []string
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CategoryName      string
}

func (q *Queries) GetProductById(ctx context.Context, id pgtype.UUID) (GetProductByIdRow, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i GetProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.ShortDescription,
		&i.Price,
		&i.DiscountPrice,
		&i.Quantity,
		&i.LowStockThreshold,
		&i.StockStatus,
		&i.Label,
		&i.Tags,
		&i.ImagesUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.sku, p.description, p.short_description, p.price, p.discount_price, p.quantity, p.low_stock_threshold, p.stock_status, p.label, p.tags, p.images_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, c.name as category_name
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.deleted_at IS NULL 
  AND ($1::uuid IS NULL OR p.category_id = $1)
  AND ($2::text IS NULL OR p.name ILIKE $2 OR p.tags @> ARRAY[$2::text])
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type ListProductsParams struct {
	Column1 pgtype.UUID
	Column2 string
	Limit   int32
	Offset  int32
}

type ListProductsRow struct {
	ID                pgtype.UUID
	CategoryID        pgtype.UUID
	Name              string
	Slug              string
	Sku               string
	Description       string
	ShortDescription  string
	Price             pgtype.Numeric
	DiscountPrice     pgtype.Numeric
	Quantity          int32
	LowStockThreshold int32
	StockStatus       StockStatusEnum
	Label             ProductLabelEnum
	Tags              []string
	ImagesUrl         []string
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CategoryName      string
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Description,
			&i.ShortDescription,
			&i.Price,
			&i.DiscountPrice,
			&i.Quantity,
			&i.LowStockThreshold,
			&i.StockStatus,
			&i.Label,
			&i.Tags,
			&i.ImagesUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products 
SET deleted_at = CURRENT_TIMESTAMP, is_active = false 
WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET quantity = $2, stock_status = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, quantity, stock_status
`

type UpdateProductStockParams struct {
	ID          pgtype.UUID
	Quantity    int32
	StockStatus StockStatusEnum
}

type UpdateProductStockRow struct {
	ID          pgtype.UUID
	Quantity    int32
	StockStatus StockStatusEnum
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (UpdateProductStockRow, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.Quantity, arg.StockStatus)
	var i UpdateProductStockRow
	err := row.Scan(&i.ID, &i.Quantity, &i.StockStatus)
	return i, err
}
