// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 05_coupons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    coupon_code, description, discount_type, value, min_order_amount, 
    max_discount_amount, usage_limit, usage_limit_per_user, start_date, expiry_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, coupon_code, description, discount_type, value, min_order_amount, max_discount_amount, usage_limit, usage_limit_per_user, used_count, start_date, expiry_date, is_active, created_at, updated_at, deleted_at
`

type CreateCouponParams struct {
	CouponCode        string
	Description       pgtype.Text
	DiscountType      DiscountTypeEnum
	Value             pgtype.Numeric
	MinOrderAmount    pgtype.Numeric
	MaxDiscountAmount pgtype.Numeric
	UsageLimit        pgtype.Int4
	UsageLimitPerUser pgtype.Int4
	StartDate         pgtype.Timestamptz
	ExpiryDate        pgtype.Timestamptz
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.CouponCode,
		arg.Description,
		arg.DiscountType,
		arg.Value,
		arg.MinOrderAmount,
		arg.MaxDiscountAmount,
		arg.UsageLimit,
		arg.UsageLimitPerUser,
		arg.StartDate,
		arg.ExpiryDate,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.Description,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxDiscountAmount,
		&i.UsageLimit,
		&i.UsageLimitPerUser,
		&i.UsedCount,
		&i.StartDate,
		&i.ExpiryDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, coupon_code, description, discount_type, value, min_order_amount, max_discount_amount, usage_limit, usage_limit_per_user, used_count, start_date, expiry_date, is_active, created_at, updated_at, deleted_at FROM coupons 
WHERE coupon_code = $1 AND is_active = true AND deleted_at IS NULL AND expiry_date > CURRENT_TIMESTAMP 
LIMIT 1
`

func (q *Queries) GetCouponByCode(ctx context.Context, couponCode string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, couponCode)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.Description,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxDiscountAmount,
		&i.UsageLimit,
		&i.UsageLimitPerUser,
		&i.UsedCount,
		&i.StartDate,
		&i.ExpiryDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const trackCouponUsage = `-- name: TrackCouponUsage :exec
UPDATE coupons 
SET used_count = used_count + 1, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

func (q *Queries) TrackCouponUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, trackCouponUsage, id)
	return err
}
