// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 06_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, quantity, unit_price
) VALUES (
    $1, $2, $3, $4
) RETURNING id, order_id, product_id, quantity, unit_price, total_price
`

type CreateOrderItemParams struct {
	OrderID   pgtype.UUID
	ProductID pgtype.UUID
	Quantity  int32
	UnitPrice pgtype.Numeric
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
	)
	return i, err
}

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :exec
INSERT INTO order_status_histories (
    order_id, changed_by, previous_shipping_status, new_shipping_status, remarks
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateOrderStatusHistoryParams struct {
	OrderID                pgtype.UUID
	ChangedBy              pgtype.UUID
	PreviousShippingStatus NullShippingStatusEnum
	NewShippingStatus      ShippingStatusEnum
	Remarks                pgtype.Text
}

func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, createOrderStatusHistory,
		arg.OrderID,
		arg.ChangedBy,
		arg.PreviousShippingStatus,
		arg.NewShippingStatus,
		arg.Remarks,
	)
	return err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, order_unique_id, user_id, coupon_code, shipping_name, shipping_phone, shipping_district, shipping_thana, shipping_full_address, special_notes, subtotal, discount_amount, shipping_amount, total_amount, payment_method, payment_status, shipping_status, is_payment_verified, created_at, updated_at FROM orders WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderById(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderUniqueID,
		&i.UserID,
		&i.CouponCode,
		&i.ShippingName,
		&i.ShippingPhone,
		&i.ShippingDistrict,
		&i.ShippingThana,
		&i.ShippingFullAddress,
		&i.SpecialNotes,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.ShippingAmount,
		&i.TotalAmount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.ShippingStatus,
		&i.IsPaymentVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, order_unique_id, user_id, coupon_code, shipping_name, shipping_phone, shipping_district, shipping_thana, shipping_full_address, special_notes, subtotal, discount_amount, shipping_amount, total_amount, payment_method, payment_status, shipping_status, is_payment_verified, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUserOrdersParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUserOrders, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderUniqueID,
			&i.UserID,
			&i.CouponCode,
			&i.ShippingName,
			&i.ShippingPhone,
			&i.ShippingDistrict,
			&i.ShippingThana,
			&i.ShippingFullAddress,
			&i.SpecialNotes,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingAmount,
			&i.TotalAmount,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.ShippingStatus,
			&i.IsPaymentVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placeOrder = `-- name: PlaceOrder :one
INSERT INTO orders (
    order_unique_id, user_id, coupon_code, shipping_name, shipping_phone,
    shipping_district, shipping_thana, shipping_full_address, special_notes,
    subtotal, discount_amount, shipping_amount, total_amount, payment_method
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, order_unique_id, user_id, coupon_code, shipping_name, shipping_phone, shipping_district, shipping_thana, shipping_full_address, special_notes, subtotal, discount_amount, shipping_amount, total_amount, payment_method, payment_status, shipping_status, is_payment_verified, created_at, updated_at
`

type PlaceOrderParams struct {
	OrderUniqueID       string
	UserID              pgtype.UUID
	CouponCode          pgtype.Text
	ShippingName        string
	ShippingPhone       string
	ShippingDistrict    string
	ShippingThana       string
	ShippingFullAddress string
	SpecialNotes        pgtype.Text
	Subtotal            pgtype.Numeric
	DiscountAmount      pgtype.Numeric
	ShippingAmount      pgtype.Numeric
	TotalAmount         pgtype.Numeric
	PaymentMethod       PaymentMethodEnum
}

func (q *Queries) PlaceOrder(ctx context.Context, arg PlaceOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, placeOrder,
		arg.OrderUniqueID,
		arg.UserID,
		arg.CouponCode,
		arg.ShippingName,
		arg.ShippingPhone,
		arg.ShippingDistrict,
		arg.ShippingThana,
		arg.ShippingFullAddress,
		arg.SpecialNotes,
		arg.Subtotal,
		arg.DiscountAmount,
		arg.ShippingAmount,
		arg.TotalAmount,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderUniqueID,
		&i.UserID,
		&i.CouponCode,
		&i.ShippingName,
		&i.ShippingPhone,
		&i.ShippingDistrict,
		&i.ShippingThana,
		&i.ShippingFullAddress,
		&i.SpecialNotes,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.ShippingAmount,
		&i.TotalAmount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.ShippingStatus,
		&i.IsPaymentVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET shipping_status = $2, payment_status = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, order_unique_id, user_id, coupon_code, shipping_name, shipping_phone, shipping_district, shipping_thana, shipping_full_address, special_notes, subtotal, discount_amount, shipping_amount, total_amount, payment_method, payment_status, shipping_status, is_payment_verified, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID             pgtype.UUID
	ShippingStatus ShippingStatusEnum
	PaymentStatus  PaymentStatusEnum
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.ShippingStatus, arg.PaymentStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderUniqueID,
		&i.UserID,
		&i.CouponCode,
		&i.ShippingName,
		&i.ShippingPhone,
		&i.ShippingDistrict,
		&i.ShippingThana,
		&i.ShippingFullAddress,
		&i.SpecialNotes,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.ShippingAmount,
		&i.TotalAmount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.ShippingStatus,
		&i.IsPaymentVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
