// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 07_payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id, transaction_id, amount, payment_method, status, raw_gateway_response
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, order_id, transaction_id, amount, payment_method, status, raw_gateway_response, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID            pgtype.UUID
	TransactionID      pgtype.Text
	Amount             pgtype.Numeric
	PaymentMethod      PaymentMethodEnum
	Status             PaymentStatusEnum
	RawGatewayResponse []byte
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.TransactionID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Status,
		arg.RawGatewayResponse,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TransactionID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Status,
		&i.RawGatewayResponse,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, raw_gateway_response = $3, paid_at = CASE WHEN $2 = 'paid'::payment_status_enum THEN CURRENT_TIMESTAMP ELSE paid_at END, updated_at = CURRENT_TIMESTAMP
WHERE transaction_id = $1
RETURNING id, order_id, transaction_id, amount, payment_method, status, raw_gateway_response, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	TransactionID      pgtype.Text
	Status             PaymentStatusEnum
	RawGatewayResponse []byte
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.TransactionID, arg.Status, arg.RawGatewayResponse)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TransactionID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Status,
		&i.RawGatewayResponse,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
