// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 08_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    product_id, user_id, rating, description
) VALUES (
    $1, $2, $3, $4
) RETURNING id, product_id, user_id, rating, description, status, created_at, updated_at
`

type CreateReviewParams struct {
	ProductID   pgtype.UUID
	UserID      pgtype.UUID
	Rating      int32
	Description string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Description,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductReviews = `-- name: ListProductReviews :many
SELECT r.id, r.product_id, r.user_id, r.rating, r.description, r.status, r.created_at, r.updated_at, u.full_name as user_name 
FROM reviews r
JOIN users u ON r.user_id = u.id
WHERE r.product_id = $1 AND r.status = 'approved'
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductReviewsParams struct {
	ProductID pgtype.UUID
	Limit     int32
	Offset    int32
}

type ListProductReviewsRow struct {
	ID          pgtype.UUID
	ProductID   pgtype.UUID
	UserID      pgtype.UUID
	Rating      int32
	Description string
	Status      ReviewStatusEnum
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserName    string
}

func (q *Queries) ListProductReviews(ctx context.Context, arg ListProductReviewsParams) ([]ListProductReviewsRow, error) {
	rows, err := q.db.Query(ctx, listProductReviews, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductReviewsRow
	for rows.Next() {
		var i ListProductReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewStatus = `-- name: UpdateReviewStatus :one
UPDATE reviews
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, user_id, rating, description, status, created_at, updated_at
`

type UpdateReviewStatusParams struct {
	ID     pgtype.UUID
	Status ReviewStatusEnum
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewStatus, arg.ID, arg.Status)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
