// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        int64
	UserID    int64
	ProductID int64
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Payment struct {
	ID        int64
	OrderID   int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Product struct {
	ID            int64
	Name          string
	Description   pgtype.Text
	ImageUrl      pgtype.Text
	Slug          string
	Price         pgtype.Numeric
	IsStock       bool
	StockQuantity int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserProfile struct {
	ID        int64
	UserID    int64
	Bio       pgtype.Text
	Address   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
