// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateOrUpdateProfile(ctx context.Context, arg CreateOrUpdateProfileParams) (UserProfile, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetCategoryById(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCouponByCode(ctx context.Context, couponCode string) (Coupon, error)
	GetOrderById(ctx context.Context, id pgtype.UUID) (Order, error)
	GetProductById(ctx context.Context, id pgtype.UUID) (GetProductByIdRow, error)
	GetProfileByUserId(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error)
	ListProductReviews(ctx context.Context, arg ListProductReviewsParams) ([]ListProductReviewsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	PlaceOrder(ctx context.Context, arg PlaceOrderParams) (Order, error)
	SoftDeleteCategory(ctx context.Context, id pgtype.UUID) error
	SoftDeleteProduct(ctx context.Context, id pgtype.UUID) error
	TrackCouponUsage(ctx context.Context, id pgtype.UUID) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (UpdateProductStockRow, error)
	UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) (Review, error)
	UpdateUserOne(ctx context.Context, id pgtype.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
